timesheets/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from main.views import EmployeeDetailView, TimesheetCreateView, TimesheetDetailView, LogOffView, LogInView, \
    RegisterEmployeeView, TeamCreateView, TeamListView, TeamJoinStaffView, TeamJoinManagerView, TeamViewMembersListView, \
    TeamLeaveStaffView, TeamLeaveManagerView, ManagerTeamViewMembersListView, TeamDeleteView, \
    PenaltyCreateView, PenaltyTypeCreateView, PenaltyDeleteView, PenaltyTypeDeleteView, \
    EmployeeUpdateView, ClaimCreateView, HomeView, TimesheetClaimListView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('employee/<slug:slug>', EmployeeDetailView.as_view(), name='employee-detail'),
    path('employee-update/<slug:slug>', EmployeeUpdateView.as_view(), name='employee-update'),
    path('logout', LogOffView.as_view(), name='logout'),
    path('login', LogInView.as_view(), name='login'),
    path('register', RegisterEmployeeView.as_view(), name='register-employee'),
    path('create', TimesheetCreateView.as_view(), name='timesheet-create'),
    path('timesheet-detail/<int:pk>', TimesheetDetailView.as_view(), name='timesheet-detail'),
    path('penalty-claim', ClaimCreateView.as_view(), name='penalty-claim'),
    path('penalty-create', PenaltyCreateView.as_view(), name='penalty-create'),
    path('penalty-delete/<int:pk>', PenaltyDeleteView.as_view(), name='penalty-delete'),
    path('penalty-type-create', PenaltyTypeCreateView.as_view(), name='penalty-type-create'),
    path('penalty-type-delete/<int:pk>', PenaltyTypeDeleteView.as_view(), name='penalty-type-delete'),
    path('team-create', TeamCreateView.as_view(), name='team-create'),
    path('team-delete/<slug:slug>', TeamDeleteView.as_view(), name='team-delete'),
    path('team-list', TeamListView.as_view(), name='team-list'),
    path('team-join-staff/<int:team_id>', TeamJoinStaffView.as_view(), name='team-join-staff'),
    path('team-leave-staff/<int:team_id>', TeamLeaveStaffView.as_view(), name='team-leave-staff'),
    path('team-join-manager/<int:team_id>', TeamJoinManagerView.as_view(), name='team-join-manager'),
    path('team-leave-manager/<int:team_id>', TeamLeaveManagerView.as_view(), name='team-leave-manager'),
    path('team-detail/<int:team_id>', TeamViewMembersListView.as_view(), name='team-view-members-list'),
    path('manager-team-member-list', ManagerTeamViewMembersListView.as_view(), name='manager-team-member-list'),
    path('claim', TimesheetClaimListView.as_view(), name='timesheet-claim')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db.models.query import QuerySet
from django.contrib.auth.models import AbstractUser, Group
from django.core.exceptions import ValidationError
from django.db import models
from datetime import datetime, timedelta
import autoslug
from django.urls import reverse


class PenaltyType(models.Model):
    name = models.TextField()

    def __str__(self):
        return self.name

    @property
    def is_used(self):
        return Penalty.objects.filter(penalty_type=self).count() > 0

    def calculate_available_employee_time(self, employee: 'Employee'):
        employee_timesheets = Timesheet.objects.filter(penalty__penalty_type=self, employee=employee)
        employee_claims = Claim.objects.filter(employee=employee, penalty_type=self)
        available_time = sum([ts.claimable_duration.total_seconds() for ts in employee_timesheets])
        claimed_time = sum([claim.claimed_seconds for claim in employee_claims])
        return (available_time - claimed_time) / 3600


class Penalty(models.Model):
    penalty_types = [
        ('PD', 'Paid'),
        ('TL', 'Toil')
    ]
    name = models.TextField()
    penalty_type = models.CharField(max_length=2, choices=penalty_types, default='PD')
    # penalty_type = models.ForeignKey(PenaltyType, on_delete=models.RESTRICT)
    valid_for_day_count = models.IntegerField(default=14)
    base_threshold = models.IntegerField(default=7200)

    def __str__(self):
        return self.name


class Employee(AbstractUser):
    team = models.ForeignKey('Team', on_delete=models.RESTRICT, null=True, blank=True)
    slug = autoslug.AutoSlugField(populate_from='get_full_name', unique=True, null=True)
    tutorial_done = models.BooleanField(default=False)

    def __str__(self):
        return f'[{self.username}] {self.first_name} {self.last_name}'

    def add_timesheet(self, start_date_time: datetime, duration: int, penalty: Penalty):
        ts = Timesheet.objects.create(employee=self,
                                      start_date_time=start_date_time,
                                      _duration=duration,
                                      penalty=penalty)
        ts.save()

    def add_claim(self, penalty_type: PenaltyType, claimed_seconds: int):
        claimed = Claim.objects.create(employee=self,
                                       penalty=penalty_type,
                                       claimed_seconds=claimed_seconds)
        claimed.save()

    @property
    def last_5_time_sheets(self):
        time_sheets = Timesheet.objects.filter(employee=self).order_by(
            'start_date_time').reverse()[:5]
        return time_sheets

    @property
    def last_5_claims(self):
        return Claim.objects.filter(employee=self).order_by('claim_date').reverse()[:5]

    @property
    def total_time_sheets_submitted(self) -> int:
        time_sheets = Timesheet.objects.filter(employee=self)
        return time_sheets.count()

    @property
    def total_claims_submitted(self):
        claim = Claim.objects.filter(employee=self)
        return claim.count()

    @property
    def duration_per_penalty(self):
        """
        Gets available claimable time in hours for each penalty type.

        :return: List[Dictionary{penalty:PenaltyType, available: Int}
        """
        penalties = PenaltyType.objects.all()
        durations = []
        for penalty in penalties:
            durations.append({'penalty_type': penalty,
                              'available': penalty.calculate_available_employee_time(self)})
        return durations

    @property
    def is_manager(self):
        if self.groups:
            try:
                self.groups.get(name='Manager')
                return True
            except KeyError:
                return False
        else:
            return False


class Team(models.Model):
    name = models.TextField()
    manager = models.ForeignKey(Employee, on_delete=models.RESTRICT, related_name='team_manager', blank=True, null=True)
    slug = autoslug.AutoSlugField(populate_from='name', unique=True, null=True)

    def __str__(self):
        return self.name

    def add_employee(self, employee: Employee):
        """
        Add an employee to the team.

        :param employee: Employee object
        """
        if employee.team:
            raise ValidationError(f'Error, staff already in team "{employee.team.name}".')
        employee.team = self
        employee.save()

    def add_manager(self, employee: Employee):
        """
        Adds the employee to the team using self.add_employee then adds the employee to the Manager group.

        :param employee: Employee object
        """
        if self.manager:
            raise ValidationError(f'Team already has a manager, "{self.manager.name}".')

        self.add_employee(employee)  # Add Employee to the team

        manager_group = Group.objects.get(name='Manager')  # Add Employee to the Manager group
        manager_group.user_set.add(employee)
        manager_group.save()
        self.manager = employee  # Set the teams manager to the Employee
        self.save()

    def remove_employee(self, employee: Employee):
        """
        Removes an employee from a team.

        :param employee: Employee object
        """
        if employee.team != self:
            raise ValidationError('Employee isn\'t a member of this team.')
        if employee.team is None:
            raise ValidationError('Employee isn\'t a member of a team.')
        employee.team = None
        employee.save()

    def remove_manager(self, employee: Employee):
        """
        Removes the employee from the team using self.remove_employee then removes the employee from the Manager group.
        Finally sets the team manager to None.

        :param employee: Employee object
        """
        if self.manager != employee:
            raise ValidationError('Employee isn\'t the manager of this team.')

        self.remove_employee(employee)  # Remove Employee from the team

        manager_group = Group.objects.get(name='Manager')  # Remove Employee from the Manager group
        manager_group.user_set.remove(employee)
        manager_group.save()

        self.manager = None  # Remove the team manager.
        self.save()

    @property
    def staff_count(self):
        return Employee.objects.filter(team=self).count()

    @property
    def duration_per_penalty(self) -> list:
        # todo Needs to match the Employee duration_per_penalty, to make rendering the same on the templates.
        """
        Gets available claimable time in hours for each penalty type for the team.

        :return: List[Dictionary{penalty:PenaltyType, available: Int}]
        """
        durations = {}
        for employee in Employee.objects.filter(team=self):
            for penalty in employee.duration_per_penalty:
                try:
                    durations[penalty['penalty_type'].name] += penalty['available']
                except KeyError:
                    durations[penalty['penalty_type'].name] = penalty['available']
        return list(zip(list(durations), list(durations.values())))


def get_hours_left(ts):
    return 24 - (ts.hour + ts.minute / 60)


class Timesheet(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.RESTRICT)
    start_date_time = models.DateTimeField()
    _duration = models.IntegerField()
    penalty = models.ForeignKey(Penalty, on_delete=models.RESTRICT)
    claim = models.ForeignKey('TimesheetClaim', blank=True, null=True, on_delete=models.RESTRICT)

    def save(self, *args, **kwargs):
        super(Timesheet, self).save(*args, **kwargs)
        self.create_time_sheet_row()
        self.create_time_sheet_cost_row()

    def create_time_sheet_row(self):
        diff = self.end_date_time - self.start_date_time

        # Worked Time is all within one day.
        if self.start_date_time.date() == self.end_date_time.date():
            TimesheetRow.objects.create(date_worked=self.start_date_time.date(),
                                        worked_seconds=self.duration.total_seconds(),
                                        payout_seconds=self._calculate_payout_amount_in_seconds(
                                            day=self.start_date_time.date(),
                                            seconds=self.duration.total_seconds()),
                                        timesheet_id=self.pk)
        else:
            # Worked Time is on multiple days.
            start = self.start_date_time
            for day in range(diff.days + bool(diff.seconds) + 1):
                if start.date() != self.end_date_time.date():
                    hours_remaining = get_hours_left(start)
                else:
                    hours_remaining = self.end_date_time.hour + self.end_date_time.minute / 60
                TimesheetRow.objects.create(date_worked=start.date(),
                                            worked_seconds=round(hours_remaining * 3600),
                                            payout_seconds=self._calculate_payout_amount_in_seconds(
                                                day=start.date(),
                                                seconds=round(hours_remaining * 3600)),
                                            timesheet=self)

                start = start + timedelta(hours=hours_remaining)

    def create_time_sheet_cost_row(self):
        if self.start_date_time.date() == self.end_date_time.date():
            # Worked Time is all within one day.
            self._calculate_and_create_cost_codes(self.start_date_time.date(), self._duration, 0)
        else:
            # Worked Time is on multiple days.
            start = self.start_date_time
            diff = self.end_date_time - self.start_date_time
            prior_day_time = 0
            for day in range(diff.days + bool(diff.seconds) + 1):
                if start.date() != self.end_date_time.date():

templates/main/claim_form.html
{% extends 'base.html' %}
{% block title %}Create{% endblock %}
{% block content %}
    <div>
        <h4 class="my-4 text-center">Claim time</h4>
    </div>
    <div class="d-flex flex-row justify-content-center my-4 mt-3">
        {% for penalty_type in user.duration_per_penalty %}
            <div class="card m-2" style="width: 8rem;">
                <div class="card-body text-center">
                    <h3 class="card-title pb-2">{{ penalty_type.available|floatformat:2 }}
                    </h3>
                    <h6 class="card-subtitle mb-1 text-muted">
                        {{ penalty_type.penalty_type }} HRS
                        </h6>

                </div>
            </div>
        {% endfor %}
    </div>
    {% include 'main/floating_validation_form.html' with button_name='Claim' %}
{% endblock %}

templates/main/employee_detail.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}


{% block content %}
    <main class="container p-3">
        {% if not user == employee %}
            <div class="d-flex flex-row justify-content-between align-items-center my-3 pb-3"><h3
                    class="m-0">{{ employee.get_full_name }}</h3>
                <div><a class="btn btn-sm btn-success me-2" href="{% url 'employee-update' employee.slug %}">Edit</a><a
                        class="btn btn-sm btn-dark me-2" href="{% url 'manager-team-member-list' %}">Back</a></div>
            </div>
        {% endif %}
        <div class="d-flex flex-row justify-content-center flex-wrap gap-3">
            <div class="card" style="width: 8rem;">
                <div class="card-body text-center">
                    <h3 class="card-title pb-2">{{ employee.total_time_sheets_submitted }}</h3>
                    <h6 class="card-subtitle text-muted">
                        Sheet{% if employee.total_time_sheets_submitted > 1 %}s{% endif %}</h6>
                </div>
            </div>
            <div class="card" style="width: 8rem;">
                <div class="card-body text-center">
                    <h3 class="card-title pb-2">{{ employee.total_claims_submitted }}</h3>
                    <h6 class="card-subtitle mb-1 text-muted">
                        Claim{% if employee.total_claims_submitted > 1 %}s{% endif %}</h6>
                </div>
            </div>
            {% for duration in employee.duration_per_penalty %}
                <div class="card" style="width: 8rem;">
                    <div class="card-body text-center">
                        <h3>{{ duration.available|floatformat:2 }}</h3>
                        <h6 class="text-muted">{{ duration.penalty_type.name|lower|capfirst }} hrs</h6>

                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="mt-3">
            <h3 class="py-3">Latest Time Sheets</h3>
            <div id="recent_items" class="accordion accordion-flush">
                {% if not  employee.last_5_time_sheets %}
                    <small class="fst-italic">{% if employee == user %}You {% else %}They {% endif %}haven't submitted
                        any time sheets.</small>
                {% endif %}
                {% for time_sheet in employee.last_5_time_sheets %}
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="heading-{{ time_sheet.pk }}">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapse-{{ time_sheet.pk }}" aria-expanded="false"
                                    aria-controls="collapse-{{ time_sheet.pk }}">
                                {{ time_sheet.start_date_time|date:"d M Y" }}
                            </button>
                        </h2>
                        <div id="collapse-{{ time_sheet.pk }}" class="accordion-collapse collapse"
                             aria-labelledby="heading-{{ time_sheet.pk }}" data-bs-parent="#recent_items">
                            <div class="accordion-body">
                                <div class="d-flex flex-column">
                                    <div class="d-flex flex-row justify-content-between">
                                        <div class="align-middle">Worked: {{ time_sheet.duration }}</div>
                                        <a href="{% url 'timesheet-detail' time_sheet.pk %}"
                                           class="btn btn-sm btn-outline-dark py-0">View</a>
                                    </div>
                                    <div>
                                        Accrued: {{ time_sheet.accrued_duration }}
                                    </div>
                                    <div>
                                        Type: {{ time_sheet.penalty.penalty_type.name|lower|capfirst }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="mt-3">
            <h3 class="py-3">Latest Claims</h3>
            <div id="recent_claims" class="accordion accordion-flush pb-5">
                {% if not  employee.last_5_time_sheets %}
                    <small class="fst-italic">{% if employee == user %}You {% else %}They {% endif %}haven't submitted
                        any claims.</small>
                {% endif %}
                {% for claim in employee.last_5_claims %}
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="heading-claim-{{ claim.pk }}">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapse-claim-{{ claim.pk }}" aria-expanded="false"
                                    aria-controls="collapse-claim-{{ claim.pk }}">
                                {{ claim.claim_date|date:"d M Y" }}
                            </button>
                        </h2>
                        <div id="collapse-claim-{{ claim.pk }}" class="accordion-collapse collapse"
                             aria-labelledby="heading-claim-{{ claim.pk }}" data-bs-parent="#recent_claims">
                            <div class="accordion-body">
                                <div class="d-flex flex-column">
                                    <div class="d-flex flex-row justify-content-between">
                                        <div class="align-middle">Claimed: {{ claim.duration }}</div>
                                        {#                                        <a href="{% url 'timesheet-detail' claim.pk %}"#}
                                        {#                                           class="btn btn-sm btn-outline-dark py-0">View</a>#}
                                    </div>
                                    <div>
                                        Type: {{ claim.penalty_type.name|lower|capfirst }}
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>
    {% if user == employee and user.team %}
        <div class="position-fixed bottom-0 end-0 me-4 mb-4 d-flex flex-row align-content-between">
            <a class="border p-3 bg-dark"
               style="border-radius: 20px; z-index: 3;"
               href="{% url 'timesheet-create' %}">
                <span class="material-icons text-center align-middle text-white">add</span>
            </a>
            <a class="border p-3 bg-success mx-3"
               style="border-radius: 20px; z-index: 3;"
               href="{% url 'penalty-claim' %}">
                <span class="material-icons text-center align-middle text-white">paid</span>
            </a>
        </div>

    {% endif %}
{% endblock %}

templates/main/employee_form.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}


{% block content %}
    <main class="container p-3">
        {% if not user == employee %}
            <div class="d-flex flex-row justify-content-between align-items-center mt-3"><h3 class="m-0">
                Edit {{ employee.get_full_name }}</h3>
                <div><a class="btn btn-sm btn-dark me-2" href="{% url 'manager-team-member-list' %}">Back</a></div>
            </div>
            {% else %}
            <div class="d-flex flex-row justify-content-between align-items-center mt-3"><h3 class="m-0">
                Edit {{ user.get_full_name }}</h3>
                <div><a class="btn btn-sm btn-dark me-2" href="{% url 'home' %}">Back</a></div>
            </div>
        {% endif %}
    {% include 'main/floating_validation_form.html' with button_name='Update' %}
    </main>
{% endblock %}

templates/main/floating_validation_form.html
<form method="post" class="mt-4" novalidate>{% csrf_token %}
    {% if form.errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Holy guacamole!</strong> {{ form.non_field_errors }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
    {% for field in form.hidden_fields %}
        {{ field }}
    {% endfor %}
    {% for field in form.visible_fields %}
        <div class="form-floating mb-3">
            {{ field }}
            <label for="id_{{ field.name }}">{{ field.label }}</label>
            <div id="{{ field.label|cut:" "|lower }}Feedback" class="invalid-feedback fst-italic px-1 m-0">
                {{ field.errors.as_text|cut:"*" }}
            </div>
        </div>
    {% endfor %}
    <div class="d-flex flex-row justify-content-end">
        {% if back_referer %}
        <a class="btn p-3 px-3 mt-3 me-5" href="{{ request.META.HTTP_REFERER }}">Back</a>
        {% elif back_home %}
        <a class="btn p-3 px-3 mt-3 me-5" href="{% url 'home' %}">Back</a>
        {% elif back_custom %}
        <a class="btn p-3 px-3 mt-3 me-5" href="{{ back_custom }}">Back</a>
        {% endif %}
        <button type="submit" class="btn btn-dark p-3 px-5 mt-3">{{ button_name }}</button>
    </div>
</form>

templates/main/manager_team_members_list.html
{% extends 'base.html' %}

{% block title %}Manage Team{% endblock %}

{% block content %}
    <main class="container p-3 ">
        <h1 class="py-3">{{ team.name }}</h1>
        <table class="table">
            <thead>
            <tr>
                <th>Employee</th>
                {% for penalty_type in user.duration_per_penalty %}
                    <th>{{ penalty_type.penalty_type }}</th>
                {% endfor %}

            </tr>
            </thead>
            <tbody>
            {% for employee in employee_list %}
                <tr>
                    <td><a href="{% url 'employee-detail' employee.slug %}">{{ employee.get_full_name }}</a></td>
                    {% for penalty_type in employee.duration_per_penalty %}
                        <td>{{ penalty_type.available|floatformat:2 }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <td>Totals</td>
                {% for penalty_type in team.duration_per_penalty %}
                    <td>{{ penalty_type.1|floatformat:2 }}</td>
                {% endfor %}
            </tr>
            </tfoot>
        </table>
    </main>

{% endblock %}

templates/main/penalty_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Deletion{% endblock %}

{% block content %}
    <main class="container p-3 pt-5">
        <form method="post">{% csrf_token %}
            <h1 class="pb-4">Confirm Deletion</h1>
            Are you sure want to delete the "{{ object }}" Penalty?
            <div class="d-flex flex-row justify-content-end">
                <a class="btn p-3 px-5 mt-3 me-3" href="{{ request.META.HTTP_REFERER }}">Back</a>
                <button type="submit" class="btn btn-danger p-3 px-5 mt-3">Delete</button>
            </div>
        </form>
    </main>

{% endblock %}

templates/main/penalty_form.html
{% extends 'base.html' %}
{% block title %}Create Penalty{% endblock %}
{% block content %}
    <section class="container pt-3">
    <h1>Create Penalty</h1>
        <table class="table table-sm mt-5">
            <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Penalty Type
                </th>
                <th>Days Valid</th>
                <th>
                    Actions
                </th>
            </tr>
            </thead>
            <tbody>
            {% for p in penalties %}
                <tr>
                    <td>{{ p.name }}</td>
                    <td>{{ p.penalty_type.name }}</td>
                    <td>{{ p.valid_for_day_count }}</td>
                    <td>
                        <a href="{% url 'penalty-delete' p.pk %}" class="btn btn-sm btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            <form method="post">{% csrf_token %}
                <tfoot>
                <tr>
                    <td>
                        {{ form.name }}
                    </td>

                    <td>
                        {{ form.penalty_type }}
                    </td>
                    <td>{{ form.valid_for_day_count }}</td>
                    <td>
                        <button type="submit" class="btn btn-sm btn-success">Add</button>
                    </td>
                </tr>
                </tfoot>
            </form>


        </table>
       <div class="d-flex flex-row justify-content-end">
            <a class="btn p-3 px-3 mt-3 me-3" href="{% url 'home' %}">Back</a>
        </div>
    </section>


{% endblock %}

templates/main/penaltytype_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Deletion{% endblock %}

{% block content %}
    <main class="container p-3 pt-5">
        <form method="post">{% csrf_token %}
            <h1 class="pb-4">Confirm Deletion</h1>
            Are you sure want to delete the "{{ object }}" Penalty Type?
            <div class="d-flex flex-row justify-content-end">
                <a class="btn p-3 px-5 mt-3 me-3" href="{{ request.META.HTTP_REFERER }}">Back</a>
                <button type="submit" class="btn btn-danger p-3 px-5 mt-3">Delete</button>
            </div>

        </form>

    </main>

{% endblock %}

templates/main/penaltytype_form.html
{% extends 'base.html' %}
{% block title %}Create Penalty{% endblock %}
{% block content %}
    <section class="container pt-3">
        <h1>Create Penalty Type</h1>
        <table class="table table-sm mt-5">
            <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Actions
                </th>
            </tr>
            </thead>
            <tbody>
            {% for p in penalty_types %}
                <tr>
                    <td>{{ p.name }}</td>
                    <td>
                        <a href="#" class="btn btn-sm btn-warning">Edit</a>
                        {% if p.is_used %}
                            <span class="d-inline-block" tabindex="0" data-bs-toggle="tooltip"
                                  data-bs-placement="bottom" title="There are still penalties using this penalty type">
                          <button class="btn btn-sm btn-danger" type="button" disabled>Delete</button>
                        </span>
                        {% else %}
                            <a href="{% url 'penalty-type-delete' p.pk %}"
                               class="btn btn-sm btn-danger">Delete</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            <form method="post" class="">{% csrf_token %}
                <tfoot>
                <tr>
                    <td>
                        {{ form.name }}
                    </td>
                    <td>
                        <button type="submit" class="btn btn-sm btn-success">Add</button>
                    </td>
                </tr>
                </tfoot>
            </form>


        </table>
        <div class="d-flex flex-row justify-content-end">
            <a class="btn p-3 px-3 mt-3 me-3" href="{% url 'home' %}">Back</a>
        </div>
    </section>


{% endblock %}

templates/main/register_form.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
    <main class="container p-3">
        <div class="h3 text-center mt-4 mb-3">
            User Registration
        </div>
        {% include 'main/floating_validation_form.html' with button_name='Register' %}
        <div class="d-flex flex-row justify-content-end mt-3">
            <small class="fst-italic">Already Registered?
                <a href="{% url 'login' %}" class="text-decoration-none text-muted">Log in</a></small>
        </div>
    </main>
{% endblock %}

templates/main/team_form.html
{% extends 'base.html' %}

{% block title %}Create Team{% endblock %}

{% block content %}
    <main class="container p-3">
        <h1 class="my-4">Create Team</h1>
        {% include 'main/floating_validation_form.html' with button_name='Save' back_home='True' %}
    </main>
{% endblock %}

templates/main/team_members_list.html
{% extends 'base.html' %}

{% block title %}Team Members{% endblock %}

{% block content %}
    <main class="container p-3">
    <h3 class="py-3">{{ team.name }}</h3>
        <table  style="width: 100%;">
            <thead>
            <tr>
                <th style="width: 60%;">Name</th>
            </tr>
            </thead>
            <tbody>
            {% for employee in object_list %}
                <tr>
                    <td>{{ employee.get_full_name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
             <div class="d-flex flex-row justify-content-end">
            <a class="btn p-3 px-3 mt-3 me-3" href="{% url 'team-list' %}">Back</a>
        </div>
    </main>


{% endblock %}

templates/main/timesheet_form.html
{% extends 'base.html' %}
{% block title %}Create{% endblock %}
{% block content %}
    <div>
        <h4 class="my-4 text-center">New Timesheet</h4>
    </div>
    {% include 'main/floating_validation_form.html' with button_name='Create' %}
{% endblock %}